server:
  port: 8081

spring:
  datasource:
#    url: jdbc:postgresql://host.docker.internal:5432/ordersdb
    url: jdbc:postgresql://host.docker.internal:5432/ordersdb

    username: postgres
    password: Shifal@0786
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:8080/realms/simpleshop
          jwk-set-uri: http://host.docker.internal:8080/realms/simpleshop/protocol/openid-connect/certs

keycloak:
  url: http://host.docker.internal:8080
  realm: simpleshop
  client-id: simpleshopapi
  client-secret: MLQur72i08U64Fi5eTM2QGjYHMEjF5dv
  admin:
    username: admin
    password: newpassword123
    client-id: admin-cli

api:
  customer:
    base: /api/customers